--- !ruby/object:Provision::Config::Config
serial_version_id: 1f5bf7b09312097817fe40e9fc3ec504247c1bef
vm_name: devbox
base_memory: 32768
disk_space: 500
processors: 12
video_memory: 128
monitor_count: 1
timezone: ''
extra_mounts:
  Projects: ".."
  LocalProjects: "C:/Users/jacky/LocalProjects"
extra_steps:
  MyConfigsSteps: "../my-configs/src/steps.rb"
